name: ci

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read
  packages: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: ghcr.io/webmastercamp/${{ github.event.repository.name }}-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy
        uses: WebmasterCamp/deploy-action@main
        with:
          image: ghcr.io/webmastercamp/${{ github.event.repository.name }}-backend@${{ steps.build-and-push.outputs.digest }}
          deploymentName: backend
          port: 3000
        env:
          PORT: ${{ secrets.PORT }}
          TZ: ${{ secrets.TZ }}
          DATABASE_TABLE_PREFIX: ${{ secrets.DATABASE_TABLE_PREFIX }}
          DATABASE_POSTGRESQL_HOST: ${{ secrets.DATABASE_POSTGRESQL_HOST }}
          DATABASE_POSTGRESQL_PORT: ${{ secrets.DATABASE_POSTGRESQL_PORT }}
          DATABASE_POSTGRESQL_USERNAME: ${{ secrets.DATABASE_POSTGRESQL_USERNAME }}
          DATABASE_POSTGRESQL_PASSWORD: ${{ secrets.DATABASE_POSTGRESQL_PASSWORD }}
          DATABASE_POSTGRESQL_DBNAME: ${{ secrets.DATABASE_POSTGRESQL_DBNAME }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags: ghcr.io/webmastercamp/${{ github.event.repository.name }}-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy
        uses: WebmasterCamp/deploy-action@main
        with:
          image: ghcr.io/webmastercamp/${{ github.event.repository.name }}-frontend@${{ steps.build-and-push.outputs.digest }}
          deploymentName: frontend
          port: 3000
